import { Router } from "express";
import { authMiddleware } from "../../middlewares/auth.middleware";
import { isAdmin } from "../../middlewares/isAdmin.middleware";
import { requireRoles } from "../../middlewares/role.middleware";
import { validate } from "../../middlewares/validation.middleware";
import { leadCaptureRateLimiter } from "../../middlewares/rateLimit.middleware";
import leadController from "./lead.controller";
import { convertLeadSchema, createLeadActivitySchema, createLeadSchema, createLeadTaskSchema, importLeadsSchema, publicCaptureLeadSchema, updateLeadSchema, updateLeadTaskSchema } from "./lead.validation";

const router = Router();
router.post("/public", leadCaptureRateLimiter, validate(publicCaptureLeadSchema), leadController.capturePublicLead);
router.use(authMiddleware, isAdmin);
router.get("/pipeline", leadController.pipeline);
router.get("/board", leadController.board);
router.get("/follow-ups", leadController.followUps);
router.get("/owners", leadController.owners);
router.post("/import", requireRoles("owner", "admin", "manager", "dispatcher"), validate(importLeadsSchema), leadController.importLeads);
router.get("/", leadController.listLeads);
router.post("/", requireRoles("owner", "admin", "manager", "dispatcher", "support"), validate(createLeadSchema), leadController.createLead);
router.get("/:id", leadController.getLead);
router.patch("/:id", requireRoles("owner", "admin", "manager", "dispatcher"), validate(updateLeadSchema), leadController.updateLead);
router.post("/:id/convert", requireRoles("owner", "admin", "manager", "dispatcher"), validate(convertLeadSchema), leadController.convertLead);
router.post("/:id/activities", requireRoles("owner", "admin", "manager", "dispatcher", "support"), validate(createLeadActivitySchema), leadController.recordActivity);
router.post("/:id/tasks", requireRoles("owner", "admin", "manager", "dispatcher", "support"), validate(createLeadTaskSchema), leadController.createTask);
router.patch("/:id/tasks/:taskId", requireRoles("owner", "admin", "manager", "dispatcher", "support"), validate(updateLeadTaskSchema), leadController.updateTask);
export default router;
