import { Router } from "express";
import portalController from "./portal.controller";
import { portalAuthMiddleware } from "./portal.middleware";
import { validate } from "../../middlewares/validation.middleware";
import { createRateLimiter } from "../../middlewares/rateLimit.middleware";
import { exchangePortalLinkSchema, portalCancelSchema, portalProfileSchema, portalRescheduleSchema, requestPortalLinkSchema } from "./portal.validation";

const router = Router();
router.use((_req, res, next) => { res.setHeader("Cache-Control", "private, no-store"); res.setHeader("Pragma", "no-cache"); next(); });
const authLimiter = createRateLimiter({ namespace: "portal-auth", windowMs: 15 * 60 * 1000, max: 12 });
router.post("/auth/request", authLimiter, validate(requestPortalLinkSchema), portalController.requestLink);
router.post("/auth/exchange", authLimiter, validate(exchangePortalLinkSchema), portalController.exchange);
router.use(portalAuthMiddleware);
router.get("/session", portalController.session);
router.post("/logout", portalController.logout);
router.get("/overview", portalController.overview);
router.get("/bookings", portalController.bookings);
router.get("/bookings/:id", portalController.booking);
router.post("/bookings/:id/cancel", validate(portalCancelSchema), portalController.cancel);
router.post("/bookings/:id/reschedule", validate(portalRescheduleSchema), portalController.reschedule);
router.get("/bookings/:id/rebook", portalController.rebook);
router.get("/invoices", portalController.invoices);
router.post("/invoices/:id/pay", portalController.payInvoice);
router.get("/payments", portalController.payments);
router.patch("/profile", validate(portalProfileSchema), portalController.profile);
router.get("/notifications", portalController.notifications);
router.patch("/notifications/read-all", portalController.markAllRead);
router.patch("/notifications/:id/read", portalController.markRead);
export default router;
