import type { WebsiteSnapshot } from "./website.validation";

export const DEFAULT_WEBSITE_SNAPSHOT: WebsiteSnapshot = {
  branding: {
    siteName: "BIO Cleaning",
    tagline: "Back In Order",
    logoUrl: "https://res.cloudinary.com/dr6linfry/image/upload/q_auto/f_auto/v1778514293/logo_fekjaa.jpg",
    faviconUrl: "",
  },
  announcement: {
    enabled: false,
    text: "Now booking recurring home and office cleaning.",
    linkLabel: "Book now",
    linkUrl: "/book",
  },
  hero: {
    eyebrow: "Eco · Trusted · Punctual",
    title: "A cleaner space, restored with intention.",
    description: "Professional home and office cleaning with trained teams, eco-conscious products, precise scheduling, and a quality check before we leave.",
    mediaUrl: "",
    mediaAlt: "Luxury home interior after professional cleaning",
    primaryCta: { label: "Book cleaning", url: "/book" },
    secondaryCta: { label: "Get a quote", url: "/quote" },
    trustItems: ["5,100+ happy clients", "4.9 average rating", "Fully insured", "Same-day booking"],
  },
  statistics: [
    { id: "spaces", value: 5100, decimals: 0, suffix: "+", label: "spaces restored" },
    { id: "rating", value: 4.9, decimals: 1, suffix: "", label: "average rating" },
    { id: "arrival", value: 98, decimals: 0, suffix: "%", label: "on-time arrival" },
    { id: "eco", value: 100, decimals: 0, suffix: "%", label: "eco-first supplies" },
  ],
  homepageSections: [
    { id: "full-service", type: "full_service", enabled: true, order: 10, eyebrow: "Full service", title: "Cleaning that feels considered from arrival to handoff.", subtitle: "Routine service, deep cleaning, moving-day resets, and commercial care all run through one consistent operating standard.", body: "", mediaUrl: "" },
    { id: "service-finder", type: "service_finder", enabled: true, order: 15, eyebrow: "Find your clean", title: "Start with the space. We’ll guide the service.", subtitle: "Use this quick finder or go straight to the full live booking experience.", body: "", mediaUrl: "" },
    { id: "how-we-clean", type: "how_we_clean", enabled: true, order: 20, eyebrow: "How we clean", title: "A repeatable method behind every spotless handoff.", subtitle: "The process is thorough without feeling chaotic inside your home or workplace.", body: "", mediaUrl: "" },
    { id: "equipment", type: "equipment", enabled: true, order: 30, eyebrow: "Equipment & products", title: "Professional tools, chosen for the surface.", subtitle: "", body: "", mediaUrl: "" },
    { id: "before-after", type: "before_after", enabled: true, order: 35, eyebrow: "Before + after", title: "See the finishing standard.", subtitle: "A visual reset backed by the same field checklist used on every job.", body: "", mediaUrl: "" },
    { id: "services", type: "services", enabled: true, order: 40, eyebrow: "Services", title: "Our range of cleaning services", subtitle: "One trusted team for every type of space — handled with the same eco-friendly care.", body: "", mediaUrl: "" },
    { id: "why-choose", type: "why_choose", enabled: true, order: 50, eyebrow: "Why BIO", title: "Quality you can feel when you walk back in.", subtitle: "", body: "", mediaUrl: "" },
    { id: "team", type: "team", enabled: true, order: 55, eyebrow: "Our team", title: "People you can trust inside the space.", subtitle: "Meet the team behind the quality standard.", body: "", mediaUrl: "" },
    { id: "process", type: "process", enabled: true, order: 60, eyebrow: "Simple process", title: "From booking to spotless in a few clear steps.", subtitle: "", body: "", mediaUrl: "" },
    { id: "testimonials", type: "testimonials", enabled: true, order: 70, eyebrow: "Testimonials", title: "What clients say after the clean", subtitle: "", body: "", mediaUrl: "" },
    { id: "satisfaction", type: "satisfaction", enabled: true, order: 80, eyebrow: "Trusted service", title: "A cleaning partner customers come back to.", subtitle: "", body: "", mediaUrl: "" },
    { id: "service-areas", type: "service_areas", enabled: true, order: 90, eyebrow: "Service areas", title: "Professional cleaning across the communities we serve.", subtitle: "", body: "", mediaUrl: "" },
    { id: "booking-preview", type: "booking_preview", enabled: true, order: 95, eyebrow: "Online booking", title: "Book from live capacity—without waiting for a callback.", subtitle: "Real pricing, duration, availability and payment policy in one flow.", body: "", mediaUrl: "" },
    { id: "faq", type: "faq", enabled: true, order: 100, eyebrow: "FAQ", title: "Helpful questions about our services", subtitle: "Clear answers before you book, with human support whenever you need it.", body: "", mediaUrl: "" },
    { id: "cta", type: "cta", enabled: true, order: 110, eyebrow: "Limited offer", title: "Ready to bring it back in order?", subtitle: "Get 20% off your first cleaning when you book this week.", body: "", mediaUrl: "", cta: { label: "Book now", url: "/book" } },
  ],
  about: {
    eyebrow: "Eco-Certified Since 2017",
    title: "We Are BIO Cleaning",
    intro: "Back In Order — restoring your space, restoring your peace of mind.",
    storyTitle: "A Simple Belief: Every Space Deserves to Be Spotless",
    storyParagraphs: [
      "Founded in 2017, BIO Cleaning started with a commitment to reliable service and safer products. Today our team serves homes and businesses with the same attention to detail.",
      "Every clean follows a clear scope, careful product selection, and a final quality check.",
    ],
    mission: "To deliver effortless, eco-conscious cleaning that gives every household and business back the time and calm they deserve.",
    vision: "A world where professional cleaning never compromises health — for people, pets, or the planet.",
    mediaUrl: "",
    values: [
      { id: "eco", title: "Eco-Friendly Commitment", description: "We prioritize biodegradable, surface-appropriate products." },
      { id: "trust", title: "Reliability & Trust", description: "Vetted teams who treat customer spaces with care." },
      { id: "community", title: "Community First", description: "We build long-term relationships with the communities we serve." },
    ],
  },
  team: {
    eyebrow: "Meet The Team",
    title: "The People Behind The Sparkle",
    intro: "A trained team focused on consistent service, thoughtful communication, and quality handoff.",
    members: [],
  },
  testimonials: {
    eyebrow: "Testimonials",
    title: "Loved by homes and workplaces",
    intro: "Real feedback from customers who trust BIO Cleaning with their spaces.",
    items: [
      { id: "sarah", name: "Sarah Mitchell", role: "Homeowner", quote: "After BIO's first deep clean, our home felt brand new. Detail-obsessed and easy to work with.", rating: 5, imageUrl: "", videoUrl: "", visible: true, order: 10 },
      { id: "marcus", name: "Marcus Lee", role: "Office Manager", quote: "Reliable team, clear communication, and a consistently spotless office.", rating: 5, imageUrl: "", videoUrl: "", visible: true, order: 20 },
      { id: "priya", name: "Priya Shah", role: "Move-In Client", quote: "They handled the full move-in reset and made the apartment feel ready from day one.", rating: 5, imageUrl: "", videoUrl: "", visible: true, order: 30 },
    ],
  },
  faqs: {
    eyebrow: "FAQ",
    title: "Helpful questions about our services",
    intro: "Clear answers before you book, with human support whenever you need it.",
    items: [
      { id: "supplies", question: "Do you bring your own supplies?", answer: "Yes. Our teams arrive with the equipment and cleaning products needed for the selected service.", visible: true, order: 10 },
      { id: "pets", question: "Are your products pet-safe?", answer: "We prioritize low-residue, surface-appropriate products and can note household sensitivities in your customer preferences.", visible: true, order: 20 },
      { id: "recurring", question: "Can I set up recurring cleaning?", answer: "Yes. Weekly, bi-weekly, and monthly schedules can be booked when available.", visible: true, order: 30 },
      { id: "guarantee", question: "What if I am not satisfied?", answer: "Contact us promptly after your service and our team will review the concern and make it right under the applicable service policy.", visible: true, order: 40 },
    ],
  },
  contact: {
    heading: "Let's get your space back in order",
    intro: "Tell us what you need and our team will help with the right service, quote, or booking.",
    phone: "+1 (800) BIO-CLEAN",
    email: "hello@biocleaningllc.com",
    hours: "Mon–Fri 7am–8pm · Sat 8am–6pm",
    address: "",
    serviceAreaSummary: "Serving New York, New Jersey & Boston",
    mapEmbedUrl: "",
  },
  socialLinks: [],
  serviceAreas: [
    { id: "ny", name: "New York", description: "Residential and commercial cleaning in supported New York service zones.", visible: true, order: 10 },
    { id: "nj", name: "New Jersey", description: "Professional cleaning for supported New Jersey communities.", visible: true, order: 20 },
    { id: "boston", name: "Boston", description: "Cleaning availability across supported Greater Boston service zones.", visible: true, order: 30 },
  ],
  policies: {
    privacy: "BIO Cleaning respects your privacy. We collect information needed to provide services, manage bookings, communicate with you, process payments, and improve our operations. Contact us for privacy questions or data requests.",
    terms: "By using this website or booking BIO Cleaning services, you agree to provide accurate information, follow applicable service instructions, and pay charges disclosed before confirmation. Service-specific terms shown in estimates, bookings, or invoices also apply.",
    cancellation: "Cancellation and rescheduling windows may vary by service. The applicable policy is displayed during booking and stored with your booking confirmation. Contact support if you need help changing an appointment.",
    accessibility: "BIO Cleaning aims to provide an accessible website and service experience. If you encounter a barrier, contact our team and we will provide reasonable assistance or an alternative way to access the information or service.",
  },
  seo: {
    siteTitle: "BIO Cleaning",
    titleTemplate: "%s | BIO Cleaning",
    defaultDescription: "Professional residential and commercial cleaning with trained teams, convenient online booking, and thoughtful service.",
    keywords: ["house cleaning", "office cleaning", "commercial cleaning", "deep cleaning", "online cleaning booking"],
    ogImageUrl: "",
    robotsIndex: true,
    robotsFollow: true,
  },
};
