import { Router } from "express";
import schedulingController from "./scheduling.controller";
import { authMiddleware } from "../../middlewares/auth.middleware";
import { isAdmin } from "../../middlewares/isAdmin.middleware";
import { requireRoles } from "../../middlewares/role.middleware";
import { validate } from "../../middlewares/validation.middleware";
import { createScheduleBlockSchema, createStaffScheduleSchema, updateScheduleBlockSchema, updateSchedulingSettingsSchema, updateStaffScheduleSchema } from "./scheduling.validation";

const router = Router();
router.get("/public", schedulingController.getPublicConfig);
router.use(authMiddleware, isAdmin);
router.get("/settings", schedulingController.getSettings);
router.patch("/settings", requireRoles("owner", "admin", "manager"), validate(updateSchedulingSettingsSchema), schedulingController.updateSettings);
router.get("/staff", schedulingController.listStaff);
router.post("/staff", requireRoles("owner", "admin", "manager"), validate(createStaffScheduleSchema), schedulingController.createStaff);
router.patch("/staff/:id", requireRoles("owner", "admin", "manager"), validate(updateStaffScheduleSchema), schedulingController.updateStaff);
router.delete("/staff/:id", requireRoles("owner", "admin", "manager"), schedulingController.deleteStaff);
router.get("/blocks", schedulingController.listBlocks);
router.post("/blocks", requireRoles("owner", "admin", "manager", "dispatcher"), validate(createScheduleBlockSchema), schedulingController.createBlock);
router.patch("/blocks/:id", requireRoles("owner", "admin", "manager", "dispatcher"), validate(updateScheduleBlockSchema), schedulingController.updateBlock);
router.delete("/blocks/:id", requireRoles("owner", "admin", "manager", "dispatcher"), schedulingController.deleteBlock);
export default router;
