import { Router } from "express";
import quoteController from "./quote.controller";
import { validate } from "../../middlewares/validation.middleware";
import { idempotency } from "../../middlewares/idempotency.middleware";
import { authMiddleware } from "../../middlewares/auth.middleware";
import { isAdmin } from "../../middlewares/isAdmin.middleware";
import { requireRoles } from "../../middlewares/role.middleware";
import { bookingRateLimiter } from "../../middlewares/rateLimit.middleware";
import { createQuoteSchema, publicAcceptQuoteSchema, publicConvertQuoteSchema, updateQuoteSchema } from "./quote.validation";
const router=Router();
router.get("/public/:token",bookingRateLimiter,quoteController.publicGet);
router.post("/public/:token/accept",bookingRateLimiter,idempotency("quote-public-accept"),validate(publicAcceptQuoteSchema),quoteController.publicAccept);
router.post("/public/:token/decline",bookingRateLimiter,quoteController.publicDecline);
router.post("/public/:token/convert",bookingRateLimiter,idempotency("quote-public-convert"),validate(publicConvertQuoteSchema),quoteController.publicConvert);
router.use(authMiddleware,isAdmin);
router.get("/",quoteController.list);
router.post("/",requireRoles("owner","admin","manager","dispatcher","support"),validate(createQuoteSchema),quoteController.create);
router.get("/:id",quoteController.get);
router.patch("/:id",requireRoles("owner","admin","manager"),validate(updateQuoteSchema),quoteController.update);
router.post("/:id/send",requireRoles("owner","admin","manager","dispatcher","support"),quoteController.send);
export default router;
