import { Response } from "express";
import httpStatus from "http-status";
import { asyncHandler } from "../../lib/errorsHandle";
import { response } from "../../lib/response";
import { ProtectedRequest } from "../../types/protected-request";
import invoiceService from "./invoice.services";
const list=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const r=await invoiceService.listInvoices(req.query);res.status(httpStatus.OK).json(response({message:"Invoices retrieved successfully",status:"OK",statusCode:httpStatus.OK,data:r.invoices,type:r.meta}));});
const get=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.getInvoice(req.params.id);res.status(httpStatus.OK).json(response({message:"Invoice retrieved successfully",status:"OK",statusCode:httpStatus.OK,data}));});
const update=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.updateInvoice(req.params.id,req.body);res.status(httpStatus.OK).json(response({message:"Invoice updated",status:"OK",statusCode:httpStatus.OK,data}));});
const send=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.sendInvoice(req.params.id);res.status(httpStatus.OK).json(response({message:"Invoice sent successfully",status:"OK",statusCode:httpStatus.OK,data}));});
const payAdmin=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.payAdmin(req.params.id);res.status(httpStatus.OK).json(response({message:"Payment link prepared",status:"OK",statusCode:httpStatus.OK,data}));});
const manual=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.recordManualPayment(req.params.id,req.body.amount,req.body.note,req.user?._id);res.status(httpStatus.OK).json(response({message:"Manual payment recorded",status:"OK",statusCode:httpStatus.OK,data}));});
const voidInvoice=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.voidInvoice(req.params.id);res.status(httpStatus.OK).json(response({message:"Invoice voided",status:"OK",statusCode:httpStatus.OK,data}));});
const startRecurring=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.startRecurring(req.params.id);res.status(httpStatus.OK).json(response({message:"Recurring billing checkout prepared",status:"OK",statusCode:httpStatus.OK,data}));});
const cancelRecurring=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.cancelRecurring(req.params.id);res.status(httpStatus.OK).json(response({message:"Recurring billing canceled",status:"OK",statusCode:httpStatus.OK,data}));});
const summary=asyncHandler(async(_req:ProtectedRequest,res:Response)=>{const data=await invoiceService.financeSummary();res.status(httpStatus.OK).json(response({message:"Finance summary retrieved",status:"OK",statusCode:httpStatus.OK,data}));});
const publicGet=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.publicInvoice(req.params.token);res.status(httpStatus.OK).json(response({message:"Invoice retrieved",status:"OK",statusCode:httpStatus.OK,data}));});
const publicPay=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.payPublic(req.params.token);res.status(httpStatus.OK).json(response({message:"Secure payment prepared",status:"OK",statusCode:httpStatus.OK,data}));});
const publicStartRecurring=asyncHandler(async(req:ProtectedRequest,res:Response)=>{const data=await invoiceService.startRecurringPublic(req.params.token);res.status(httpStatus.OK).json(response({message:"Recurring billing checkout prepared",status:"OK",statusCode:httpStatus.OK,data}));});
export default {list,get,update,send,payAdmin,manual,voidInvoice,startRecurring,cancelRecurring,summary,publicGet,publicPay,publicStartRecurring};
